# [참고] Hello 텐서플로 2.0 확인

In [1]:
#!pip install tensorflow

   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
    --------------------------------------- 7.9/390.3 MB 40.7 MB/s eta 0:00:10
    --------------------------------------- 8.7/390.3 MB 22.4 MB/s eta 0:00:18
   -- ------------------------------------- 23.3/390.3 MB 36.9 MB/s eta 0:00:10
   ---- ----------------------------------- 41.4/390.3 MB 48.8 MB/s eta 0:00:08
   ----- ---------------------------------- 49.5/390.3 MB 47.8 MB/s eta 0:00:08
   ----- ---------------------------------- 53.0/390.3 MB 41.6 MB/s eta 0:00:09
   ------- -------------------------------- 73.4/390.3 MB 49.3 MB/s eta 0:00:07
   -------- ------------------------------- 84.1/390.3 MB 49.7 MB/s eta 0:00:07
   ---------- ---------------------------- 106.2/390.3 MB 55.6 MB/s eta 0:00:06
   ------------- ------------------------- 130.8/390.3 MB 61.4 MB/s eta 0:00:05
   --------------- ----------------------- 150.2/390.3 MB 64.4 MB/s eta 0:00:04
   ----------------- --------------------- 173.3/39

In [1]:
#  텐서플로 2.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass



In [3]:
# Google Colab 운영체제 확인
# import platform
# print(platform.platform())

In [7]:
# 텐서플로우 불러오기, 버전 확인
import tensorflow as tf

tf.__version__

'2.19.0'


---

##  [참고] 랜덤한 수 생성

 * 균등분포란
 
     일반적으로 각 이벤트의 결과값을 알 수 없는 경우에 미래에 발생할
    이벤트의 결과값 x가 각 예상되는 범위별로  균등한 확률로 일어날 것이라고 예상될 때
   사용한다.

   예를 들어 주사위를 던져 윗면에 있는 숫자를 알아보기로 하자.  200번을 던지고 201번째    주사위를 던진다고 했을 때 201번째 결과값은 앞은 1에서 200번까지 결과값에 영향을
   받지 않는다.
   201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의
   1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
   이처럼  미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.


  * 정규분포란  
  
      과거의 축적된 경험적 데이타를 이미 보유하고 있어 이를 이용하여 미래에
    발생할 결과값 x의 각 예상되는 범위별로 발생될 확률을 어느정도 추정할 수 있을 때
    사용한다.
    세상의 수많은 현상들은  많은 경우에 있어서 정규분포를 따른다고 한다.
   
     예를 들어, 프랜차이즈 매장을  연지 2년이 되었다면  다음 달 매출액이 대략 어느
     정도 범위안에 들 것이라는 것이 예측가능하다.  이전 3개월의 매출추세를 이용해
     이번달에는 어느 범위에 들 것이라는 것이 예측가능하다.
     매장주라면 과거 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생하였으니
     이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측할 수 있고 못해도 최소
     2천만원의 매출을 달성할 수 있고,  최대 2천2백만원까지 매출할 수 있다는 예상이
     가능하다.

    많은 수학자들은  현실의 현상을 분석하여 수많은 현상들이 정규분포를 따른다는 것을
    밝혀 내고 이 정규분포가 갖고 있는 여러가지 특성들을 정리하였다.
    
    [출처](https://jonnyomme.blogspot.com/)

In [8]:
# 1) 랜덤한 수 얻기 (균일 분포)
rand = tf.random.uniform([1],0,1) # shape,   minval=0,    maxval=None,
print(rand)

tf.Tensor([0.8759407], shape=(1,), dtype=float32)


In [11]:
# 2)랜덤한 수 여러 개 얻기 (균일 분포)
rand = tf.random.uniform([4],0,1) # shape,   minval=0,    maxval=None,
print(rand)

tf.Tensor([0.15952742 0.8906002  0.39616013 0.98796153], shape=(4,), dtype=float32)


In [13]:
# 3) 랜덤한 수 여러 개 얻기 (정규 분포)
rand = tf.random.normal([4],0,1)  # shape,   mean=0.0,   stddev=1.0,
print(rand)

tf.Tensor([ 2.2946777  -0.1331406   0.35515407  0.44891214], shape=(4,), dtype=float32)


## 경사하강법

> + 경사하강법은 딥러닝 모델을 훈련할 때, 모델 태부의 가중치(weight)에 대한 미분 값을 구하고 목적함수 값이 낮아지는 방향으로 차감하면서 결국 최소 함수 값을 갖도록 하는 방법이다.

> + 딥러닝 훈련 프로세스에서 경사하강법 알고리즘을 적용하여 손실함수 값을 최소로 만드는 가충지를 찾을 수 있다




### 속도와 정확도 문제를 해결하는 고급 경사 하강법
 

가중치를 업데이트하는 방법으로 우리는 경사 하강법을 배웠습니다. 그런데 경사 하강법은 정확하게 가중치를 찾아가지만, 한 번 업데이트할 때마다 전체 데이터를 미분해야 하므로 계산량이 매우 많다는 단점이 있습니다. 이러한 점을 보완한 고급 경사 하강법이 등장하면서 딥러닝의 발전 속도는 더 빨라졌습니다.

 

◼︎ 확률적 경사 하강법

경사 하강법은 불필요하게 많은 계산량은 속도를 느리게 할 뿐 아니라, 최적 해를 찾기 전에 최적화 과정이 멈출 수도 있습니다. 확률적 경사 하강법(Stochastic Gradient Descent, SGD)은 경사 하강법의 이러한 단점을 보완한 방법입니다.

전체 데이터를 사용하는 것이 아니라, 랜덤하게 추출한 일부 데이터를 사용합니다. 일부 데이터를 사용하므로 더 빨리 그리고 자주 업데이트를 하는 것이 가능해졌습니다.

아래 그림은 경사 하강법과 확률적 경사 하강법의 차이를 보여 줍니다. 랜덤한 일부 데이터를 사용하는 만큼 확률적 경사 하강법은 중간 결과의 진폭이 크고 불안정해 보일 수도 있습니다. 하지만 속도가 확연히 빠르면서도 최적 해에 근사한 값을 찾아낸다는 장점 덕분에 경사 하강법의 대안으로 사용되고 있습니다.

<img src='./imgs/경사하강법3.PNG' width='500'/>

---

---

### [참고] 경사하강법

- 오차와 기울기의 관계를 그래프로 그려보면, 어느 한 기울기에서 오차가 최소인 점을 알 우 싱다.
- 그 점은 기울이가 0인 점이다.
- 즉, 오차가 최소인 점을 알아낼려면 기울기가 0인 점을 찾아내면 된다
- 그래서 어느 한 점을 정해두고 정해둔 학습률과 함께 미문을 하면서 이동하다보면 오차가 최소인 점을 찾게 되는데, 마치 경사를 타고 내려가는 것처럼 보여져서 이 방법을 "경사하강법"이라고 한다


<img src='./imgs/경사하강법1.png' width='500'>
<img src='./imgs/경사하강법2.png' width='500'>



---

<img src='./imgs/경사하강법4.PNG' width='500'/>

 아담(Adam)은 현재 가장 많이 사용되는 고급 경사 하강법입니다.
 


## 오차 역전파 (back propagation)

+ 신경망 내부의 가중치를 수정할 때 오차 역전파 방법을 사용
+ 경사 하강법의 확장 개념

<img src='./imgs/오차역전파.PNG' width='500'/>

 [출처] [모두의 딥러닝](https://thebook.io/080228/part03/ch09/02-02/)