 # * sklearn 라이브러리에서 간단한 분류 모델

 ## - KNN 

 
* KNN (K-Nearest Neighbors) : 최근접 분류기
	새로운 데이터가 들어오면 훈련데이타 중에서 가장 가까운 데이터 K개를 찾는다.
	이 중에서 빈도가 높은 label(결과)을 새 데이터의 레이블로 예측한다. 


<img src='./imgs/knn.png' width='500' height='380'>


### * 절차

(1) 데이타 읽어오기

(2) 데이터와 레이블 분리 변수 선언

(3) 훈련데이터와 테스트 데이터로 분리하기

(4) 모델로 학습하기

(5) 예측하기

(6) 검증하기

(7) 정확도 측정하기

In [1]:
# (1) 데이타 읽어오기

import numpy as np
from sklearn import datasets

iris = datasets.load_iris()



In [13]:
print(iris.keys())

#print(iris.DESCR)

iris.target

iris['target_names']

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
# (2) 데이터와 레이블 분리 변수 선언 ( 이미 데이터와 레이블이 정해짐 )

X = iris['data'] 
y = iris['target'] #답을 target으로 설정

print(x[:5])
print(y[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [33]:
# (3) 훈련데이터와 테스트 데이터로 분리하기
from sklearn.model_selection import train_test_split

# 기본 훈련데이터 : 75%, 테스트데이터: 25%

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0) #random_state=0 => 섞을 때 랜덤하는 규칙 번호 0 
 


print(X_train[:10])
print(X_test[:10])
print(y_train[:10])
print(y_test[:10])

#train size 가 0일때  

[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]]
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]]
[1 1 2 0 2 0 0 1 2 2]
[2 1 0 2 0 2 0 1 1 1]


In [27]:
# (4) 모델에 데이터를 학습하기
# 훈련데이타와 훈련레이블를 인자로 넣어 학습한 결과 knn 객체를 리턴한다
# n_neighbors : 이웃갯수 지정

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [35]:
# (5) 새로운 샘플 데이타가 들어왔을 때 label 예측하기
# 너무 동떨어진 데이타 입력하면 결과 예측 성능이 낮기에 기존 샘플과 유사하게 만듬
newData = np.array([[5.1, 2.9, 1., 0.3]]) 

pre_result = knn.predict(newData)
print(pre_result)

print(iris['target_names'][pre_result])

[0]
['setosa']


In [49]:
# (6) 검증하기
# 실제 레이블과 예측값의 정확도 확인
from sklearn.metrics import accuracy_score
# 테스트 데이터에 대한 예측
y_pred = knn.predict(X_test)

# 실제 정답과 예측값을 비교해 정확도 계산
accuracy = accuracy_score(y_test, y_pred)

print("정확도:", accuracy)



정확도: 0.9736842105263158


In [51]:
# (7) 정확도 측정 


a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(a==b)
print(np.mean(a==b)) # True=1, False=0 의 평균


[ True  True  True False]
0.75


In [53]:
y_predict = knn.predict(X_test)

accuracy = np.mean(y_test == y_predict)

accuracy 

0.9736842105263158

In [55]:
# (6) 검증하기 선생님 예제 
from sklearn import metrics

y_predict = knn.predict(X_test)
ac_score = metrics.accuracy_score(y_test, y_predict)
ac_score

0.9736842105263158