## 파이썬의 리스트와 튜플

[참고] 주요 기본자료형

     1- 파이썬의 리스트 / 튜플
     
     2- numpy의 dnarray
     
     3- pandas의 DataFrame / Series
     

##  리스트 복습

- append(추가요소) : 리스트 맨 마지막에 하나 추가

- pop() : 마지막요소를 지움

- extend([추가요소들]) : 리스트 마지막에 여러 개 추가

- remove('요소값') : 해당 요소값 지움

---

- insert(idx, '데이타') : 원하는 위치에 자료 삽입

---
[슬라이싱]

- 리스트명(n:m) : n부터 m-1까지 데이타 추출


In [3]:
movies = ['어밴져스','기생충','가디언스갤럭시','어떤영화','유명한 영화']
movies

['어밴져스', '기생충', '가디언스갤럭시', '어떤영화', '유명한 영화']

(1) '어젠져스2' 추가

In [5]:
movies.append('어젠져스2')

(2) 마지막요소 제거

In [7]:
movies.pop()

'어벤져스2'

(3) '어벤져스2','기생충2' 요소를 한꺼번에 추가

In [9]:
movies.extend(['어벤져스2','기생충2'])

(4) '어벤져스2' 요소 제거

In [13]:
movies.remove('어벤져스2')

(5) 네번째 위치에 '오래된 영화' 추가

In [19]:
# movies.insert(3,'오래된 영화')

movies

['어밴져스', '기생충', '가디언스갤럭시', '오래된 영화', '어떤영화', '유명한 영화', '기생충2']

(6) 영화목록에서 3번째에서 5번째까지 추출

In [17]:
movies[2:5]

['가디언스갤럭시', '오래된 영화', '어떤영화']

# 파이썬의 리스트와 넘파이 차이

1. 파이썬의 리스트

In [31]:
list = [1,2,3]
print( list * 2)
print( list * 0)
print( list * -1)

[1, 2, 3, 1, 2, 3]
[]
[]


2. 넘파이 ndarray

In [35]:
import numpy as np

ndarr = np.array([1,2,3])

print( ndarr * 2)
print( ndarr * 0)
print( ndarr * -1)

print( ndarr * 0.02)

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.02 0.04 0.06]
